nMachines = 1

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  (1..nMachines).each do |i|
    vmname = "machine#{i}"
    config.vm.define vmname.to_sym do |machine|
      machine.vm.host_name = vmname
      machine.vm.network "private_network", ip: "10.10.10.#{10+i}"
      machine.vm.provider "virtualbox" do |v|
        v.name = vmname
        v.memory = 1024
        v.cpus = 2
      end
      machine.vm.provision "shell", path: "scripts/provision.sh"
    end
  end
end
