nMachines = 1

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  (1..nMachines).each do |i|
    vmname = "machine#{i}"
    config.vm.define vmname.to_sym do |machine|
      machine.vm.host_name = vmname
      machine.vm.network "private_network", ip: "10.10.10.#{10+i}"
      machine.vm.provider "virtualbox" do |v|
        v.name = vmname
        v.memory = 1024
        v.cpus = 2
      end
      machine.vm.provision "shell", path: "scripts/provision.sh"
    end
  end
  
  if File.file?('../private/client_id')
    vmname = "machine-do"
    config.vm.define vmname.to_sym do |machine|
      machine.vm.host_name = vmname
      machine.vm.provision "shell", path: "scripts/provision.sh"
      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'digital_ocean'
        override.vm.box_url = 'https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box'
        provider.client_id = File.read('../private/client_id').strip
        provider.api_key = File.read('../private/api_key').strip
        provider.size = '1GB'
        provider.image = 'Ubuntu 12.04.4 x64'
        provider.region = 'Amsterdam 2'
      end
    end
  end
end
